config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'

  resources :users do
    collection do
    # Sign Up Routes
    post 'sign_up', to: 'registrations#create'
    get 'sign_up', to: 'registrations#new'

    # Login Routes
    post 'login', to: 'sessions#create', as: 'login'
    delete 'logout', to: 'sessions#destroy'
    get 'login', to: 'sessions#new'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  mount_uploader :profile_photo, ProfilePhotoUploader

  before_save :downcase_email

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  validates :username, presence: true, length: { minimum: 5 }, uniqueness: true
  validates :profile_photo, presence: true

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication

  before_action :current_user
  helper_method :current_user
  helper_method :user_signed_in?
end

app/controllers/concerns/authentication.rb
module Authentication
  def login(user)
    reset_session
    session[:current_user_id] = user.id
  end

  def logout
    reset_session
  end

  def redirect_if_authenticated
    redirect_to root_path, alert: 'You are already logged in.' if user_signed_in?
  end

  private

  def current_user
    @current_user ||= session[:current_user_id] && User.find_by(id: session[:current_user_id])
  end

  def user_signed_in?
    @current_user.present?
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < UsersController
  before_action :redirect_if_authenticated, only: [:create, :new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.with(user: @user).welcome_email.deliver_now
      redirect_to root_path, notice: "Successfully created account"
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < UsersController
  before_action :redirect_if_authenticated, only: [:create, :new]

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if @user.authenticate(params[:user][:password])
        login @user
        redirect_to root_path, notice: 'Signed in.'
      else
        flash.now[:alert] = 'Incorrect password.'
        render :new, status: :unprocessable_entity
      end
    else
      flash.now[:alert] = 'Incorrect email'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Signed out.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update destroy]

  def index
    redirect_to login_users_path unless user_signed_in?
    @users = User.order(id: :asc)
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to users_path
      UserMailer.with(user: @user).update_email.deliver_now if current_user.email != @user.email
    else
      render :edit, status: :bad_request
    end
  end

  def destroy
    @user.destroy

    redirect_to login_users_path, notice: "User Deleted Successfully"
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :profile_photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMailer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <% flash.each do |type, msg| %>
      <div class="w-25 mx-auto my-5 alert alert-info">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_form.html.erb
<div class="container w-50">
  <%= form_with model: user, url: url do |form| %>

    <% if user.errors.any? %>
      <div class="w-75 bg-secondary bg-opacity-25 shadow rounded">
        <ul class="text-danger">
          <% user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="row py-3">
      <div class="col-6 col-sm-3">
        <%= form.label :username, class: "form-label" %>
      </div>
      <div class="col-6">
        <%= form.text_field :username, required: true, class: "form-control" %>
      </div>
    </div>

    <div class="row py-3">
      <div class="col-6 col-sm-3">
        <%= form.label :email, class: "form-label" %>
      </div>
      <div class="col-6">
        <%= form.email_field :email, required: true, class: "form-control" %>
      </div>
    </div>

    <% unless controller.action_name == "edit" %>
      <div class="row py-3">
        <div class="col-6 col-sm-3">
          <%= form.label :password, class: "form-label" %>
        </div>
        <div class="col-6">
          <%= form.password_field :password, required: true, class: "form-control" %>
        </div>
      </div>
      
      <div class="row py-3">
        <div class="col-6 col-sm-3">
          <%= form.label :password_confirmation, class: "form-label" %>
        </div>
        <div class="col-6">
          <%= form.password_field :password_confirmation, required: true, class: "form-control" %>
        </div>
      </div>    
    <% end %>

    <div class="row py-3">
      <div class="col-6 col-sm-3">
        <%= form.label :profile_photo, class: "form-label" %>
      </div>
      <div class="col-6">
        <%= form.file_field :profile_photo, class: "form-control" %>
      </div>
    </div>

    <div class="text-center">
      <%= form.submit class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="navbar navbar-expand-lg">
    <div class="container-fluid">
      <div>
        <%= link_to "Home", root_path, class: "col-2 navbar-brand" %>
      </div>
      <div class="d-flex justify-content-center align-items-center">
        <div class="me-3"> Welcome, 
        <% if user_signed_in? %>
          <%= current_user.username %> </div>
          <%= link_to "Sign out", logout_users_path, data: { turbo_method: :delete } , class: "btn btn-dark" %> 
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="text-center">Update User</h1>

<%= render 'shared/form', user: @user, url: user_path %>

app/views/users/index.html.erb
<h1 class="text-center m-4 h1">Users</h1>

<div class="row justify-content-center">
  <div class="col-md-10">
    <table class="table table-bordered table-striped table-hover text-center">
      <tr>
        <th>Index</th>
        <th>Username</th>
        <th>Email</th>
        <th>Profile Photo</th>
        <th>Action</th>
      </tr>
      <% @users.each_with_index do |user, inx| %>
        <tr>
          <td><%= inx+1 %></td>
          <td><%= user.username %></td>
          <td><%= user.email %></td>
          <td><%= image_tag user.profile_photo_url, alt: 'profile_photo', size: "50x50" %></td>
          <td><% if user.username == current_user.username %>
            <%= link_to 'Edit', edit_user_path(user), class: "text-decoration-none text-dark btn btn-warning me-2" %>
            <%= link_to "Destroy", user_path(user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "text-decoration-none text-light btn btn-danger" %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>